import { DifficultyLevel } from "./concept";
import { BlueprintOrigin } from "./question-blueprint";
import { QuestionType } from "./question-type";

/**
 * A persisted, LLM-generated question. Preserves provenance
 * (concept, source patterns, blueprint origin) so EKE can always
 * answer: which concept was this testing, which QuestionPattern
 * (if any) influenced it, was the blueprint evidence-derived or
 * llm-inferred, and was this generated by an LLM at all.
 *
 * `id` is a stable, unique identity used for deterministic
 * storage/retrieval — the storage *path* for a given id is
 * deterministic and idempotent to overwrite, the same as
 * ConceptSource. The question *content* itself is not
 * reproducible (it came from an LLM call), which is an inherent
 * property of generation, not a gap in this model.
 */
export interface GeneratedQuestion {
  id: string;

  conceptId: string;

  questionType: QuestionType;

  difficulty: DifficultyLevel;

  questionText: string;

  /** Present when questionType requires discrete options (e.g. mcq). */
  options?: string[];

  correctAnswer: string;

  explanation: string;

  /** QuestionPattern ids that influenced this question. Empty when llm-inferred. */
  sourcePatternIds: string[];

  origin: BlueprintOrigin;

  generatedBy: "llm";

  createdAt: string;
}
